# =============================
# Data Plane API Configuration
# =============================
dataplaneapi:
  host: 0.0.0.0
  port: 5555
  schemes:
    - http
    # - https  # Uncomment and configure for production
  api_base_path: /v3

  # TLS Configuration (Uncomment and configure for production)
  # tls:
  #   cert_file: /etc/ssl/private/api-cert.pem
  #   key_file: /etc/ssl/private/api-key.pem
  #   verify_client: false

  haproxy:
    config_file: /usr/local/etc/haproxy/haproxy.cfg
    haproxy_bin: /usr/local/sbin/haproxy
    reload_delay: 5
    reload_cmd: "kill -SIGUSR2 1"
    reload_retention: 1
    config_version: 3
    master_runtime_api: /var/run/haproxy.sock
    connection_timeout: 5

  # User authentication (use secure credentials in production)
  users:
    - username: ${HAPROXY_API_USER:-admin}
      password: ${HAPROXY_API_PASS:-admin}
      insecure: true

  transaction:
    transaction_dir: /etc/haproxy/dataplaneapi
    max_open_transactions: 20
    max_transaction_age: 600

  log_targets:
    - log_to: stdout
      log_level: info

  api_detailed_errors: true
  disable_version_check: true
  debug: false  # Set to true only for troubleshooting

# End of configuration
