dataplaneapi:
  host: 0.0.0.0
  port: 5555  # Use the same port to avoid confusion
  schemes:
    - http

  # HAProxy configuration
  haproxy:
    config_file: /usr/local/etc/haproxy/haproxy.cfg
    haproxy_bin: /usr/local/sbin/haproxy
    reload_delay: 5
    reload_cmd: "kill -SIGUSR2 1"
    reload_retention: 1
    config_version: 3

  # User authentication
  users:
    - username: admin
      password: admin
      insecure: true

  # Storage for transactions
  transaction:
    transaction_dir: /etc/haproxy/dataplaneapi
    max_open_transactions: 20

  # Log configuration
  log_targets:
    - log_to: stdout
      log_level: debug

  # API version and features
  api_detailed_errors: true
  
  # Don't check API versions which can cause compatibility issues
  disable_version_check: true

  # Enable debugging for troubleshooting
  debug: true
