dataplaneapi:
  host: 0.0.0.0
  port: 5555 # Use the same port to avoid confusion
  schemes:
    - http
    # Uncomment the following line in production to use HTTPS
    # - https
  api_base_path: /v3

  # TLS Configuration (Uncomment in production)
  # tls:
  #   cert_file: /etc/ssl/private/api-cert.pem
  #   key_file: /etc/ssl/private/api-key.pem
  #   verify_client: false

  # HAProxy configuration
  haproxy:
    config_file: /usr/local/etc/haproxy/haproxy.cfg
    haproxy_bin: /usr/local/sbin/haproxy
    reload_delay: 5
    reload_cmd: "kill -SIGUSR2 1"
    reload_retention: 1
    config_version: 3
    # Additional options for more stability
    master_runtime_api: /var/run/haproxy.sock
    connection_timeout: 5

  # User authentication - in production, replace with secure credentials
  users:
    - username: ${HAPROXY_API_USER:-admin}
      password: ${HAPROXY_API_PASS:-admin}
      insecure: true

  # Storage for transactions
  transaction:
    transaction_dir: /etc/haproxy/dataplaneapi
    max_open_transactions: 20
    max_transaction_age: 600 # 10 minutes

  # Log configuration
  log_targets:
    - log_to: stdout
      log_level: info

  # API version and features
  api_detailed_errors: true

  # Don't check API versions which can cause compatibility issues
  disable_version_check: true

  # Enable debugging to help identify the issue
  debug: true
