dataplaneapi:
  host: 0.0.0.0
  port: 5555
  schemes:
    - http
  api_base_path: /v3

  haproxy:
    config_file: /usr/local/etc/haproxy/haproxy.cfg
    haproxy_bin: /usr/local/sbin/haproxy
    reload_delay: 5
    reload_strategy: custom
    ReloadCmd: "kill -SIGUSR2 1"
    RestartCmd: "/usr/local/sbin/haproxy -D -f /usr/local/etc/haproxy/haproxy.cfg -p /run/haproxy.pid -sf $(cat /run/haproxy.pid 2>/dev/null || echo 1)"
    reload_retention: 1
    config_version: 3
    master_runtime_api: /var/run/haproxy.sock
    connection_timeout: 10

  users:
    - username: admin
      password: admin
      insecure: true

  transaction:
    transaction_dir: /etc/haproxy/dataplaneapi
    max_open_transactions: 20
    max_transaction_age: 600

  resources:
    maps_dir: /etc/haproxy/maps
    ssl_certs_dir: /etc/ssl/private
    spoe_dir: /etc/haproxy/spoe

  log_targets:
    - log_to: file
      file_path: /var/log/dataplaneapi.log
      log_level: info
    - log_to: stdout
      log_level: info

  api_detailed_errors: true
  disable_version_check: true
  debug: true
