# =============================
# Data Plane API Configuration
# =============================

# Note: Moving configuration out of the 'dataplaneapi' section to the root level

host: 0.0.0.0
port: 5555
schemes:
  - http
  # - https  # Uncomment and configure for production
api_base_path: /v3

# TLS Configuration (Uncomment and configure for production)
# tls:
#   cert_file: /etc/ssl/private/api-cert.pem
#   key_file: /etc/ssl/private/api-key.pem
#   verify_client: false

haproxy:
  config_file: /usr/local/etc/haproxy/haproxy.cfg
  haproxy_bin: /usr/local/sbin/haproxy
  reload_delay: 5
  # Changed from reload_cmd to ReloadCmd (camelCase as required by Data Plane API)
  ReloadCmd: "kill -SIGUSR2 1"
  # Changed from restart_cmd to RestartCmd (camelCase as required by Data Plane API)
  RestartCmd: "kill -SIGUSR2 1 && haproxy -D -f /usr/local/etc/haproxy/haproxy.cfg -p /run/haproxy.pid -sf $(cat /run/haproxy.pid)"
  reload_retention: 1
  config_version: 3
  master_runtime_api: /var/run/haproxy.sock # Make sure this matches stats socket in haproxy.cfg
  connection_timeout: 10 # Increased timeout

# User authentication (use secure credentials in production)
users:
  - username: ${HAPROXY_API_USER:-admin}
    password: ${HAPROXY_API_PASS:-admin}
    insecure: true

transaction:
  transaction_dir: /etc/haproxy/dataplaneapi
  max_open_transactions: 20
  max_transaction_age: 600

resources:
  maps_dir: /etc/haproxy/maps
  ssl_certs_dir: /etc/ssl/private
  spoe_dir: /etc/haproxy/spoe

log_targets:
  - log_to: file
    file_path: /var/log/dataplaneapi.log
    log_level: info
  - log_to: stdout
    log_level: info

api_detailed_errors: true
disable_version_check: true
debug: true
# End of configuration
