dataplaneapi:
  host: 0.0.0.0
  port: 5555
  schemes:
    - http
  api_base_path: /v3

  haproxy:
    config_file: /usr/local/etc/haproxy/haproxy.cfg
    haproxy_bin: /usr/local/sbin/haproxy

  users:
    - username: ${HAPROXY_API_USER:-admin}
      password: ${HAPROXY_API_PASS:-admin}
      insecure: true

  transaction:
    transaction_dir: /etc/haproxy/dataplaneapi

  log_targets:
    - log_to: stdout
      log_level: info
