version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "27017:27017" # MongoDB
      - "8080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_DIR:-./config}:/config
      - ${CERTS_DIR:-./traefik-certs}:/traefik-certs
    env_file:
      - ./.env
    environment:
      - CF_EMAIL=${CF_EMAIL:-demo@example.com}
      - CF_API_KEY=${CF_API_KEY:-}
    command:
      - "--configFile=/config/traefik.yml"
    networks:
      - traefik-network
    # Improved health check that matches actual configuration
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  node-app:
    build: ./node-app
    container_name: node-app
    restart: always
    container_name: node-app
    restart: always
    ports:
      - "${NODE_PORT:-3005}:3005"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIR:-./config}:/app/config
    env_file:
      - ./.env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - APP_DOMAIN=${APP_DOMAIN:-apps.cloudlunacy.uk}
      - MONGO_DOMAIN=${MONGO_DOMAIN:-mongodb.cloudlunacy.uk}
      - DYNAMIC_CONFIG_PATH=/app/config/dynamic.yml
      - NODE_PORT=3005
      - TRAEFIK_CONTAINER=traefik
    depends_on:
      - traefik
    networks:
      - traefik-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  traefik-network:
    name: traefik-network
    external: true
