version: "3.8"

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "27017:27017"
    networks:
      - frontend
      - backend
    volumes:
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/certs:/etc/traefik/certs:ro
      - ./config/certs/acme:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - ./.env
    environment:
      - TZ=UTC
      - CF_API_KEY=${CF_API_KEY}
      - CF_ZONE_API_TOKEN=${CF_ZONE_API_TOKEN}
      - CLOUDFLARE_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${APP_DOMAIN:-cloudlunacy.uk}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.middlewares=auth-admin@consulcatalog"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - consul

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    restart: unless-stopped
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    networks:
      - frontend
      - backend
    volumes:
      - consul-data:/consul/data
    command: >
      agent -server -bootstrap-expect=1 
      -ui -client=0.0.0.0 
      -bind='{{ GetInterfaceIP "eth0" }}' 
      -advertise='{{ GetInterfaceIP "eth0" }}'
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  consul-kv-setup:
    image: hashicorp/consul:latest
    container_name: consul-kv-setup
    restart: "no"
    networks:
      - backend
    volumes:
      - ./config/consul/populate_traefik_kv.sh:/usr/local/bin/populate_traefik_kv.sh:ro
    entrypoint: "/bin/sh"
    command: >
      -c "
        echo 'Waiting for Consul to be healthy and have a leader...' &&
        while ! wget -q -O - http://consul:8500/v1/status/leader | grep -q .; do
          echo -n '.' ; sleep 2;
        done; 
        echo '\nConsul has a leader! Waiting a bit more for stability...' &&
        sleep 5 &&
        echo 'Populating KV store...' &&
        sh /usr/local/bin/populate_traefik_kv.sh
      "
    depends_on:
      consul:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
      - TRAEFIK_ADMIN_AUTH_HASH=${TRAEFIK_ADMIN_AUTH_HASH:-}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-}
      - MONGO_ROUTER_RULE=${MONGO_ROUTER_RULE:-}
      - MONGO_SERVICE_ADDRESS=${MONGO_SERVICE_ADDRESS:-}

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    networks:
      - frontend
      - backend
    volumes:
      - ./config/certs:/etc/letsencrypt
    environment:
      - CF_EMAIL=${CF_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
      - CLOUDFLARE_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CF_ZONE_API_TOKEN=${CF_ZONE_API_TOKEN}
    entrypoint: "/bin/sh -c 'sleep infinity'"

  node-app:
    build:
      context: ./node-app
      dockerfile: Dockerfile
    container_name: cloudlunacy-front
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - "${NODE_PORT:-3005}:3005"
    volumes:
      - ./logs:/app/logs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - node-app-data:/opt/cloudlunacy_front
    user: "node"
    env_file:
      - ./.env
    environment:
      - NODE_PORT=${NODE_PORT:-3005}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_DOMAIN=${MONGO_DOMAIN:-mongodb.cloudlunacy.uk}
      - APP_DOMAIN=${APP_DOMAIN:-apps.cloudlunacy.uk}
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - NODE_ENV=production
      - NODE_DEBUG=
      - LOG_DIR=/app/logs
    depends_on:
      - consul
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-app.rule=Host(`api.${APP_DOMAIN:-cloudlunacy.uk}`)"
      - "traefik.http.routers.node-app.entrypoints=websecure"
      - "traefik.http.routers.node-app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.node-app.service=node-app-svc"
      - "traefik.http.services.node-app-svc.loadbalancer.server.port=${NODE_PORT:-3005}"
      - "traefik.http.routers.node-app.middlewares=secure-headers@consulcatalog,cors-headers@consulcatalog"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${NODE_PORT:-3005}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  traefik-acme-data:
  node-app-data:
  consul-data:
    name: consul-data

networks:
  frontend:
    name: cloudlunacy-frontend
    driver: bridge
  backend:
    name: cloudlunacy-backend
    driver: bridge
