version: "3.8"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Expose dashboard port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-certs:/traefik-certs
      - ./config:/config
    environment:
      - CF_EMAIL=${CF_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    healthcheck:
      test:
        ["CMD", "wget", "-q", "--spider", "http://localhost:8080/api/rawdata"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - traefik_network

  node-app:
    build: ./node-app
    container_name: node-app
    restart: always
    depends_on:
      - traefik
    ports:
      - "${NODE_PORT}:3005"
    volumes:
      - ./config:/config
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DYNAMIC_CONFIG_PATH=/config/dynamic.yml
      - TRAEFIK_CONTAINER=traefik
      - APP_DOMAIN=${APP_DOMAIN:-apps.cloudlunacy.uk}
      - MONGO_DOMAIN=${MONGO_DOMAIN:-mongodb.cloudlunacy.uk}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - traefik_network

networks:
  traefik_network:
    driver: bridge
