version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik-dev
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard
      - "27017:27017"
    networks:
      - traefik-network
      - cloudlunacy-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik:/etc/traefik
      - ./config/certs:/etc/ssl/certs
      - ./logs:/var/log/traefik
    environment:
      - TZ=UTC
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true" # Only for development
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.mongodb.address=:27017"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  node-app:
    build:
      context: ./node-app
      dockerfile: Dockerfile.dev
    container_name: cloudlunacy-front-dev
    restart: unless-stopped
    networks:
      - traefik-network
      - cloudlunacy-network
    ports:
      - "3005:3005"
    volumes:
      - ./node-app:/app
      - ./config:/app/config
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /app/node_modules
    # Ensure directories have the right permissions before starting the container
    user: "1000:1000" # Use UID:GID that matches your host user or the node user in container
    environment:
      - NODE_PORT=3005
      - JWT_SECRET=dev_secret_key_for_testing_only
      - NODE_ENV=development
      - MONGO_DOMAIN=mongodb.localhost
      - APP_DOMAIN=apps.localhost
      - TRAEFIK_CONTAINER=traefik-dev
      - TRAEFIK_API_URL=http://traefik-dev:8080/api
      - MONGO_PORT=27017
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-app.rule=Host(`apps.localhost`)"
      - "traefik.http.routers.node-app.entrypoints=web"
      - "traefik.http.services.node-app.loadbalancer.server.port=3005"

networks:
  traefik-network:
    name: traefik-network
    driver: bridge
  cloudlunacy-network:
    name: cloudlunacy-network
    driver: bridge

volumes:
  mongodb-data:
