version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    depends_on:
      - node-app
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "27017:27017"
    networks:
      - traefik-network
      - cloudlunacy-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik
      - ./traefik-certs:/traefik-certs
      - /var/log/traefik:/var/log/traefik
    env_file:
      - ./.env
    environment:
      - TZ=UTC
      - CF_EMAIL=${CF_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
      - CLOUDFLARE_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CF_ZONE_API_TOKEN=${CF_ZONE_API_TOKEN}
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=dashboard"

  node-app:
    build:
      context: ./node-app
      dockerfile: Dockerfile
    container_name: cloudlunacy-front
    restart: always
    networks:
      - traefik-network
      - cloudlunacy-network
    ports:
      - "${NODE_PORT:-3005}:3005"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./node-app/scripts:/app/scripts
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - ./.env
    environment:
      - NODE_PORT=${NODE_PORT:-3005}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_DOMAIN=${MONGO_DOMAIN:-mongodb.cloudlunacy.uk}
      - APP_DOMAIN=${APP_DOMAIN:-apps.cloudlunacy.uk}
      - DYNAMIC_CONFIG_PATH=/app/config/dynamic.yml
      - TRAEFIK_CONTAINER=traefik
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  traefik-network:
    name: traefik-network
    external: true
  cloudlunacy-network:
    external: true
