version: "3.8"

networks:
  traefik_network:
    driver: bridge
    name: traefik_network
    attachable: true
services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - traefik_network
    volumes:
      - "./config/traefik.yml:/traefik.yml:ro"
      - "./config/dynamic.yml:/opt/traefik/dynamic.yml:rw"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--log.level=INFO"
      - "--api.insecure=false"
      - "--entrypoints.mongodb.address=:27017"
      - "--providers.docker=false"
