# Dynamic configuration for Traefik
http:
  routers:
    dashboard:
      rule: "Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      service: "api@internal"
      entryPoints:
        - "dashboard"
      middlewares:
        - "auth"

  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/" # Default admin/admin

    web-to-websecure:
      redirectScheme:
        scheme: https
        permanent: true

  services: {}

tcp:
  routers:
    mongodb-catchall:
      rule: "HostSNI(`*.mongodb.localhost`)"
      entryPoints:
        - "mongodb"
      service: "mongodb-catchall-service"
      tls:
        passthrough: true
  services:
    mongodb-catchall-service:
      loadBalancer:
        servers: []
