global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  # insecure: true # Access dashboard via http://traefik.localhost:8081, use labels for secure access

# Add ping endpoint for Docker healthchecks
ping:
  entryPoint: "web" # Use the web entrypoint for health checks

entryPoints:
  web:
    address: ":80"
    # Comment out the redirect for testing purposes
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
    #       permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "apps.cloudlunacy.uk" # From your APP_DOMAIN
            sans:
              - "*.apps.cloudlunacy.uk" # Wildcard for your app subdomains

  mongodb:
    address: ":27017" # Entrypoint for MongoDB

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: cloudlunacy-frontend # Use the frontend network defined in docker-compose

  # Enable Consul KV Provider
  consul:
    endpoints:
      - "consul:8500"
    rootKey: "traefik" # Default prefix for KV store keys

  # Enable File provider for local configuration files
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
    # Optional: Default rule template if needed globally
    # defaultRule: "Host(`{{ .Name }}.example.com`)"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "m.taibou.i@gmail.com" # Replace with your email
      storage: /etc/traefik/acme/acme.json
      # Use Cloudflare DNS challenge
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 120 # Increased delay to allow DNS propagation
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

log:
  level: Trace # Temporarily increased for troubleshooting
  # filePath: "/var/log/traefik.log" # Uncomment to log to a file inside the container

accessLog:
  {} # Enable access logs with default settings
  # filePath: "/var/log/access.log" # Uncomment to log to a file
  # format: json # Uncomment for JSON format
