global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  # insecure: true # Access dashboard via http://traefik.localhost:8081, use labels for secure access

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt # Default cert resolver
        domains:
          - main: "${APP_DOMAIN:-cloudlunacy.uk}" # Main domain from .env
            sans:
              - "api.${APP_DOMAIN:-cloudlunacy.uk}" # API subdomain
              - "traefik.${APP_DOMAIN:-cloudlunacy.uk}" # Traefik dashboard domain (if needed securely)
              # Add other domains/SANs as needed
  mongodb:
    address: ":27017" # Entrypoint for MongoDB

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: cloudlunacy-frontend # Use the frontend network defined in docker-compose

  # Enable Consul Catalog Provider
  consulCatalog:
    prefix: "traefik" # Default prefix for KV store keys
    exposedByDefault: false
    endpoint:
      address: "consul:8500" # Address of the Consul agent
      scheme: "http"
    # Optional: Default rule template if needed globally
    # defaultRule: "Host(`{{ .Name }}.example.com`)"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${CF_EMAIL}" # Your Let's Encrypt email from .env
      storage: /etc/traefik/acme/acme.json # Path inside the container to store certs
      # Use Cloudflare DNS challenge
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0 # Time to wait before checking DNS, adjust if needed
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
        # Credentials are automatically picked up from environment variables:
        # CF_API_KEY or CF_DNS_API_TOKEN, and CF_ZONE_API_TOKEN
        # Ensure these are set correctly in your .env file and passed to the traefik service

log:
  level: INFO # (DEBUG, ERROR, etc.)
  # filePath: "/var/log/traefik.log" # Uncomment to log to a file inside the container

accessLog:
  {} # Enable access logs with default settings
  # filePath: "/var/log/access.log" # Uncomment to log to a file
  # format: json # Uncomment for JSON format
