## Traefik Main Configuration

# -------------------------------
# Global settings
# -------------------------------
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# -------------------------------
# Log configuration
# -------------------------------
log:
  level: "INFO"
  format: "common"

# -------------------------------
# Access logs
# -------------------------------
accessLog:
  format: "common"

# -------------------------------
# API & dashboard
# -------------------------------
api:
  dashboard: true
  insecure: true # during initial setup

# -------------------------------
# EntryPoints
# -------------------------------
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

  traefik:
    address: ":8081" # Traefik API / dashboard

  mongodb:
    address: ":27017" # exposing Mongo for healthchecks, metrics, etc.

# -------------------------------
# Healthcheck ping
# -------------------------------
ping:
  entryPoint: traefik

# -------------------------------
# Providers
# -------------------------------
providers:
  # 1) File-based provider (dynamic config from files)
  file:
    directory: "/etc/traefik/dynamic"
    watch: true # auto-reload when files change

  # 2) Docker provider (auto-discover services via labels)
  docker:
    exposedByDefault: false

  # 3) Consul Service Catalog (Service Discovery)
  consulCatalog:
    defaultRule: "Host(`{{ normalize .Name }}.cloudlunacy.uk`)"
    exposedByDefault: false
    refreshInterval: "15s"
    connectAware: true
    providers:
      consul:
        address: "consul:8500"
        scheme: "http"

  # 4) Consul KV store (Dynamic config store)
  consul:
    rootKey: "traefik"
    endpoints:
      - "consul:8500"

# -------------------------------
# TLS options
# -------------------------------
tls:
  options:
    default:
      minVersion: "VersionTLS12"
      sniStrict: true

    mongodb:
      minVersion: "VersionTLS12"
      sniStrict: true

# -------------------------------
# Let's Encrypt
# -------------------------------
certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@cloudlunacy.uk"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: "web"
