global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  # insecure: true # Access dashboard via http://traefik.localhost:8081, use labels for secure access

# Add ping endpoint for Docker healthchecks
ping:
  entryPoint: "web" # Use the web entrypoint for health checks

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt # Default cert resolver
        domains:
          - main: "${APP_DOMAIN:-cloudlunacy.uk}" # Main domain from .env
            sans:
              - "api.${APP_DOMAIN:-cloudlunacy.uk}" # API subdomain
              - "traefik.${APP_DOMAIN:-cloudlunacy.uk}" # Traefik dashboard domain (if needed securely)
              # Add other domains/SANs as needed
  mongodb:
    address: ":27017" # Entrypoint for MongoDB

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: cloudlunacy-frontend # Use the frontend network defined in docker-compose

  # Enable Consul Catalog Provider
  consulCatalog:
    prefix: "traefik" # Default prefix for KV store keys
    exposedByDefault: false
    endpoint:
      address: "consul:8500" # Address of the Consul agent
      scheme: "http"
    # Optional: Default rule template if needed globally
    # defaultRule: "Host(`{{ .Name }}.example.com`)"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "m.taibou.i@gmail.com" # Replace with your email
      storage: /etc/traefik/acme/acme.json
      # Use Cloudflare DNS challenge
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 120 # Increased delay to allow DNS propagation
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

log:
  level: DEBUG # Temporarily increased for troubleshooting
  # filePath: "/var/log/traefik.log" # Uncomment to log to a file inside the container

accessLog:
  {} # Enable access logs with default settings
  # filePath: "/var/log/access.log" # Uncomment to log to a file
  # format: json # Uncomment for JSON format
