## Traefik Main Configuration

# Global settings
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Log configuration
log:
  level: "INFO"
  format: "common"

# Access logs configuration
accessLog:
  format: "common"

# API and dashboard configuration
api:
  dashboard: true
  insecure: true # Allow API access without authentication during setup

# Entrypoints configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

  traefik:
    address: ":8081" # Specific entrypoint for Traefik API

  mongodb:
    address: ":27017"

# Ping endpoint for Docker healthcheck
ping:
  entryPoint: traefik

# Configure providers
providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

  docker:
    exposedByDefault: false
    watch: true

  consulCatalog:
    prefix: "traefik"
    exposedByDefault: false
    refreshInterval: "30s"
    connectAware: true
    connectByDefault: false
    serviceName: "traefik"
    providers:
      consul:
        address: "consul:8500"
        scheme: "http"

  consul:
    prefix: "traefik"
    watch: true
    endpoints:
      - "consul:8500"

# TLS options
tls:
  options:
    default:
      minVersion: "VersionTLS12"
      sniStrict: true

    mongodb:
      minVersion: "VersionTLS12"
      sniStrict: true
      alpnProtocols:
        - "h2"
        - "http/1.1"

# Certificate resolvers for Let's Encrypt
certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@cloudlunacy.uk"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: "web"
