# /etc/traefik/dynamic/routes.yml

# -------------------------------
# HTTP Dynamic Configuration
# -------------------------------
http:
  routers:
    # Healthcheck endpoint on the "traefik" entryPoint
    traefik-healthcheck:
      entryPoints:
        - traefik
      rule: Path(`/ping`)
      service: api@internal

    # Secure dashboard with basic auth on HTTPS
    dashboard:
      entryPoints:
        - websecure
      rule: Host(`traefik.cloudlunacy.uk`)
      service: api@internal
      middlewares:
        - auth-admin
      tls: {}

  middlewares:
    # Basic auth for dashboard access
    auth-admin:
      basicAuth:
        users:
          - "admin:$apr1$ruca84Hq$mbjdMZBAG.KWn7vfN/SNK/" # change in production

    # Default redirect from HTTP to HTTPS
    web-to-websecure:
      redirectScheme:
        scheme: https
        permanent: true

    # Compression for HTTP responses
    compress:
      compress: {}

    # Security headers to harden HTTP
    secure-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    # CORS policy for your applications
    cors-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowOriginList:
          - "https://*.cloudlunacy.uk"
          - "https://*.apps.cloudlunacy.uk"
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true

  services:
    # Default backend service (updated dynamically by your app)
    node-app-service:
      loadBalancer:
        servers:
          - url: http://node-app:3005

# -------------------------------
# TCP Dynamic Configuration
# -------------------------------
tcp:
  routers:
    mongodb:
      entryPoints:
        - mongodb
      rule: HostSNI(`*.mongodb.cloudlunacy.uk`)
      service: mongodb
      tls:
        passthrough: true

  services:
    mongodb:
      loadBalancer:
        servers:
          - address: 127.0.0.1:27017
