# Dynamic configuration for Traefik
http:
  routers:
    # Example router for dashboard
    dashboard:
      rule: "Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      service: "api@internal"
      entryPoints:
        - "dashboard"
      middlewares:
        - "auth"

  middlewares:
    # Authentication middleware for dashboard
    auth:
      basicAuth:
        users:
          - "admin:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/" # admin:admin - PLEASE CHANGE IN PRODUCTION

    # Global redirection middleware
    web-to-websecure:
      redirectScheme:
        scheme: https
        permanent: true

  services: {}

# TCP configuration for MongoDB
tcp:
  routers:
    mongodb-catchall:
      rule: "HostSNI(`*.mongodb.cloudlunacy.uk`)"
      entryPoints:
        - "mongodb"
      service: "mongodb-catchall-service"
      tls:
        passthrough: true

  services:
    mongodb-catchall-service:
      loadBalancer:
        servers: []
