# Dynamic configuration for Traefik
http:
  routers:
    dashboard:
      rule: Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      entryPoints:
        - dashboard
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - admin:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/
    web-to-websecure:
      redirectScheme:
        scheme: https
        permanent: true
  services: {}
tcp:
  routers:
    mongodb-catchall:
      rule: "HostSNI(`*.mongodb.cloudlunacy.uk`)"
      entryPoints:
        - "mongodb"
      service: "mongodb-catchall-service"
      tls:
        certResolver: default
        domains:
          - main: "mongodb.cloudlunacy.uk"
            sans: ["*.mongodb.cloudlunacy.uk"]
  services:
    mongodb-catchall-service:
      loadBalancer:
        servers: []
        # Optional: Add TLS re-encryption to MongoDB if needed
        # serversTransport: mongodb-tls-transport
  # Optional: If you want to re-encrypt traffic to MongoDB
  serversTransports:
    mongodb-tls-transport:
      serverName: "mongodb"
      insecureSkipVerify: false
      rootCAs:
        - "/traefik-certs/ca.crt"
      certificates:
        - certFile: "/traefik-certs/client.crt"
          keyFile: "/traefik-certs/client.key"
