# Dynamic configuration for Traefik
http:
  routers:
    # Dashboard router with basic auth
    dashboard:
      rule: "Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      service: "api@internal"
      entryPoints:
        - "dashboard"
      middlewares:
        - "auth"

  middlewares:
    # Dashboard authentication middleware
    auth:
      basicAuth:
        users:
          - "admin:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"

    # Global redirection middleware - web to websecure
    web-to-websecure:
      redirectScheme:
        scheme: https
        permanent: true

  services: {}

# TCP configuration for MongoDB routing
tcp:
  routers:
    mongodb-catchall:
      rule: "HostSNI(`*.mongodb.cloudlunacy.uk`)"
      entryPoints:
        - "mongodb"
      service: "mongodb-catchall-service"
      tls:
        passthrough: true

    mongodb-240922b9-4d3b-4692-8d1c-1884d423092a:
      rule: "HostSNI(`240922b9-4d3b-4692-8d1c-1884d423092a.mongodb.cloudlunacy.uk`)"
      service: "mongodb-240922b9-4d3b-4692-8d1c-1884d423092a-service"
      entryPoints:
        - "mongodb"
      tls:
        passthrough: true

  services:
    mongodb-catchall-service:
      loadBalancer:
        servers: []

    mongodb-240922b9-4d3b-4692-8d1c-1884d423092a-service:
      loadBalancer:
        servers:
          - address: "128.140.53.203:27017"
