# Dynamic configuration for Traefik
http:
  routers: {}
  services: {}
  middlewares:
    pingMiddleware:
      ping: {}
    # Global redirection middleware - web to websecure
    web-to-websecure:
      redirectScheme:
        scheme: https
        permanent: true
