global:
  checkNewVersion: false
  sendAnonymousUsage: false
tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
  dashboard:
    address: :8081
  mongodb:
    address: :27018
    transport:
      respondingTimeouts:
        idleTimeout: 1h
api:
  dashboard: true
  insecure: true
  debug: false
ping:
  entryPoint: dashboard
log:
  level: DEBUG
  filePath: /var/log/traefik/traefik.log
  format: json
accessLog:
  filePath: /var/log/traefik/access.log
  format: json
  bufferingSize: 100
providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    watch: true
    network: traefik-network
    swarmMode: false
certificatesResolvers:
  default:
    acme:
      email: m.taibou.i@gmail.com
      storage: /etc/traefik/acme.json
      tlsChallenge: {}
