# Global settings
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Entry points definition
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  dashboard:
    address: ":8081"
  mongodb:
    address: ":27017"

# API and dashboard configuration
api:
  dashboard: true
  insecure: true

# Add ping endpoint for health checks
ping:
  entryPoint: "web"

# Log configuration
log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"

# Access logs
accessLog:
  filePath: "/var/log/traefik/access.log"

# Configure providers
providers:
  # Main dynamic configuration file
  file:
    filename: "/config/dynamic.yml"
    watch: true

  # Per-agent configuration directory
  directory:
    directory: "/config/agents"
    watch: true

  # Docker provider for container discovery
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

# Certificate resolver for HTTPS
certificatesResolvers:
  letsencrypt:
    acme:
      email: "m.taibou.i@gmail.com"
      storage: "/traefik-certs/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
