# Fixed traefik.yml with proper HTTP handling
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  mongodb:
    address: ":27017"

# Enable debug logging
log:
  level: "DEBUG"

# Access logs with detailed configuration
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: "json"
  bufferingSize: 100
  fields:
    headers:
      defaultMode: "keep"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${CF_EMAIL}"
      storage: /traefik-certs/acme.json
      # Add HTTP challenge as primary, with DNS as fallback
      httpChallenge:
        entryPoint: web
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

providers:
  file:
    filename: /config/dynamic.yml
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

api:
  dashboard: true
  # For production, replace with proper authentication
  insecure: true
  middlewares:
    - auth

# Add a basic auth middleware for securing the dashboard
http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$apr1$ruca84Hq$mbjdMZBAG.KWn7vfN/SNK/" # admin:password
