entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  mongodb:
    address: ":27017"

# Enable debug logging
log:
  level: "DEBUG"

# Access logs
accessLog: {}

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${CF_EMAIL}"
      storage: /traefik-certs/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

providers:
  file:
    filename: /config/dynamic.yml
    watch: true # Automatically reload when file changes
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

api:
  dashboard: true
  insecure: true # Only for debugging - remove in production
