# Global settings
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Entry points definition
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  dashboard:
    address: ":8081"
  mongodb:
    address: ":27017"

# API and dashboard configuration
api:
  dashboard: true
  insecure: true # Consider setting to false in production and use proper authentication
  debug: false

# Ping for healthcheck
ping:
  entryPoint: "dashboard"

# Log configuration
log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"
  format: "json"

# Access logs
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: "json"
  bufferingSize: 100

# Configure providers
providers:
  # Main dynamic configuration file
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

  # Per-agent configuration directory
  directory:
    directory: "/etc/traefik/agents"
    watch: true

  # Docker provider for container discovery
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: "traefik-network"
    swarmMode: false

# Certificate resolver for HTTPS
certificatesResolvers:
  letsencrypt:
    acme:
      email: "m.taibou.i@gmail.com"
      storage: "/traefik-certs/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# Enable tracing for debugging issues
tracing:
  serviceName: "traefik"
  jaeger:
    samplingServerURL: ""
    samplingType: "const"
    samplingParam: 1.0
