# config/traefik.yml

# Global settings
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Entry points definition - explicitly define all needed ports
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  mongodb:
    address: ":27017"
  dashboard:
    address: ":8081"

# API and dashboard configuration
api:
  dashboard: true
  insecure: true

# Log configuration
log:
  level: "INFO" # Set to DEBUG for more detailed logs during troubleshooting

# Access logs
accessLog: {}

# Configure providers
providers:
  file:
    filename: "/config/dynamic.yml"
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

# Certificate resolver for HTTPS
certificatesResolvers:
  letsencrypt:
    acme:
      email: "${CF_EMAIL}"
      storage: "/traefik-certs/acme.json"
      # Use HTTP challenge - more reliable for initial setup
      httpChallenge:
        entryPoint: "web"
