## Base Dynamic Configuration for Traefik

# HTTP Configuration
http:
  # Global middlewares
  middlewares:
    # Basic authentication for dashboard
    auth-dashboard:
      basicAuth:
        users:
          - "admin:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/" # Default admin/admin_password - change in production

    # Security headers
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    # Compression
    compress:
      compress: {}

    # Default redirect to HTTPS
    web-to-websecure:
      redirectScheme:
        scheme: https
        permanent: true

  # Default services - will be dynamically updated by the application
  services:
    node-app-service:
      loadBalancer:
        servers:
          - url: "http://node-app:3005"

# TCP Configuration for MongoDB routing
tcp:
  routers:
    # Default MongoDB router
    mongodb-default:
      entryPoints:
        - "mongodb"
      rule: "HostSNI(`*`)"
      service: "mongodb-default"
      tls:
        passthrough: true

  services:
    # Default MongoDB service - will be populated dynamically
    mongodb-default:
      loadBalancer:
        servers: []

# TLS configuration
tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_AES_128_GCM_SHA256"
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_CHACHA20_POLY1305_SHA256"
      curvePreferences:
        - "CurveP521"
        - "CurveP384"
