http:
  middlewares:
    auth-admin:
      basicAuth:
        users:
          - "admin:$apr1$ruca84Hq$mbjdMZBAG.KWn7vfN/SNK/"

    compress:
      compress: {}

    cors-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowOriginList:
          - "https://*.cloudlunacy.uk"
          - "https://*.apps.cloudlunacy.uk"
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true

    secure-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 1s
        sourceCriterion:
          ipStrategy: {}
