# Dynamic routes configuration for Traefik
# This file is managed by the CloudLunacy Front API

http:
  routers:
    traefik-healthcheck:
      entryPoints:
        - "traefik"
      rule: "Path(`/ping`)"
      service: "api@internal"
  services: {}
tcp:
  routers:
    mongodb:
      entryPoints:
        - "mongodb"
      rule: "HostSNI(`*.mongodb.cloudlunacy.uk`)"
      service: "mongodb"
      tls:
        passthrough: true
  services:
    mongodb:
      loadBalancer:
        servers:
          - address: "127.0.0.1:27017"
