name: Validate Data Plane API Configuration
on:
  push:
    paths:
      - "config/haproxy/dataplaneapi.yml"
  pull_request:
    paths:
      - "config/haproxy/dataplaneapi.yml"

jobs:
  validate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Data Plane API CLI
        run: |
          wget -qO- https://github.com/haproxytech/dataplaneapi/releases/download/v3.1.5/dataplaneapi_3.1.5_Linux_x86_64.tar.gz | sudo tar xvz -C /usr/local/bin
      - name: Validate configuration file
        run: dataplaneapi -f config/haproxy/dataplaneapi.yml --version
